name: "Quarkus compile native"
description: "Compilação nativa da aplicação quarkus"

runs:
  using: "composite"

  steps:
    - name: Configurar JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: 17
        distribution: "zulu"

    - name: Compilação nativa
      run: chmod +x ./mvnw && ./mvnw package -Pnative -DskipTests -Dquarkus.native.container-build=true
      shell: bash

    - name: Salvar artefatos
      uses: actions/upload-artifact@v2
      with:
        name: target-folder
        path: target
