name: "Quarkus compile native"
description: "Compilação nativa da aplicação quarkus"

runs:
  using: "composite"

  steps:
    - name: Configurar JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: 17
        distribution: "zulu"

    - name: Compilação nativa
      run: chmod +x ./mvnw && ./mvnw package -Pnative
      shell: bash
