name: "Cloud Run NodeJS deploy"
description: "Deploy da imagem docker no aplicativo Cloud Run NodeJS"

inputs:
  GCP_PROJECT_ID:
    description: "The project id in GCP"
    required: true
  GCP_REGION_ID:
    description: "The region id of Cloud Run in GCP for deploy"
    required: true
  CLOUD_RUN_SERVICE_ID:
    description: "The service id of Cloud Run in GCP"
    required: true
  DATABASE_NAME:
    description: "The database name of connection"
    required: false
  DATABASE_CONNECTION_STRING:
    description: "The credencial to the database connection"
    required: false

runs:
  using: "composite"

  steps:
    - uses: actions/checkout@v3

    - name: Recovery image name
      uses: actions/download-artifact@v2
      with:
        name: build-folder
        path: build

    - name: Configure Google Cloud SDK
      run: |
        echo "$GOOGLE_CLOUD_KEY" > /tmp/gcloud_key.json
        gcloud auth activate-service-account --key-file=/tmp/gcloud_key.json
        gcloud auth configure-docker us-east1-docker.pkg.dev
      shell: bash

    - name: Deploy on Cloud Run
      run: |
        IMAGE_NAME=$(cat build/image-name.txt)
        echo $IMAGE_NAME
        gcloud run deploy ${{ inputs.CLOUD_RUN_SERVICE_ID }} --project ${{ inputs.GCP_PROJECT_ID }} --platform managed --region=${{ inputs.GCP_REGION_ID }} --image $IMAGE_NAME \
        --set-env-vars "DISABLE_SIGNAL_HANDLERS=foobar
      shell: bash
