name: "NodeJS install dependencies"
description: "Instalar e cachear para as proximas as dependencies da node-modules"

runs:
  using: "composite"

  steps:
    - uses: actions/checkout@v3

    - name: Cache node modules
      id: cache-npm
      uses: actions/cache@v3
      env:
        cache-name: cache-node-modules
      with:
        # npm cache files are stored in `~/.npm` on Linux/macOS
        path: ~/.npm
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-

    - if: ${{ steps.cache-npm.outputs.cache-hit != 'true' }}
      name: Listar of dependencies
      continue-on-error: true
      shell: bash
      run: npm list

    - name: Install dependencies
      shell: bash
      run: npm install
